---
AllCops:
  TargetRubyVersion: 2.5
  
Metrics/BlockLength:
  Enabled: true
  Exclude:
    - spec/**/*
    - Rakefile

Layout/EndOfLine:
  Enabled: False

Style/FrozenStringLiteralComment:
  Enabled: false